name: macOS

on:
  pull_request:
  push:
  schedule:
    - cron: '00 21 * * *'

jobs:
  general:
    runs-on: macOS-11.0
    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew update --preinstall
          brew bundle --file=contrib/Brewfile
          pip install --user -r requirements.txt

      - name: Set ENV variables
        run: |
          . .github/workflows/gh-tools.sh

          PYTHONUSERBASE="${HOME}/python_packages"
          PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig:$PKG_CONFIG_PATH"
          THREADS="$(sysctl -n hw.physicalcpu)"
          CONFIGURE_FLAGS="
            --with-ivykis=system
            --disable-sun-streams
            --disable-systemd
            --disable-pacct
            --disable-smtp
            --enable-all-modules
            --with-python=3
          "

          gh_export PYTHONUSERBASE PKG_CONFIG_PATH THREADS CONFIGURE_FLAGS
          gh_path "/usr/local/opt/bison/bin:/usr/local/opt/libnet/bin:${PYTHONUSERBASE}/bin"

      - name: autogen.sh
        run: |
          ./autogen.sh

      - name: configure
        run: |
          ./configure ${CONFIGURE_FLAGS}

      - name: make
        run: |
          set -e

          make --keep-going -j ${THREADS} || \
            { \
              S=$?; \
              make V=1; \
              return $S; \
            }

      - name: make check
        run: |
          set -e

          make --keep-going check -j ${THREADS} || \
            { \
              S=$?; \
              echo "Output of first test invocation:"; \
              find . -name test-suite.log | xargs cat; \
              make V=1 check; \
              echo "Output of second test invocation:"; \
              find . -name test-suite.log | xargs cat; \
              return $S; \
            }
